<?php

declare(strict_types=1);

namespace App\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class MyceliumConfiguration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('mycelium');

        $treeBuilder->getRootNode()
            ->children()
                ->arrayNode('security')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('state_manager')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('class')
                                    ->defaultValue('App\Service\State\RedisStateManager')
                                    ->info('State manager implementation class')
                                ->end()
                                ->integerNode('key_length')
                                    ->defaultValue(32)
                                    ->min(8)
                                    ->max(128)
                                    ->info('Length of generated state keys')
                                ->end()
                                ->scalarNode('key_prefix')
                                    ->defaultValue('rwl:state:')
                                    ->info('Prefix for state keys in storage')
                                ->end()
                                ->scalarNode('ttl')
                                    ->defaultValue((int)\ini_get('session.gc_maxlifetime'))
                                    ->validate()
                                        ->ifTrue(function ($v) {
                                            return null !== $v && (!is_numeric($v) || (int)$v <= 0);
                                        })
                                        ->thenInvalid('TTL must be a positive integer or null')
                                    ->end()
                                    ->info('Time to live for state keys in seconds (null for session.gc_maxlifetime)')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('mfa')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('email')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->integerNode('code_length')
                                            ->defaultValue(6)
                                            ->min(4)
                                            ->max(12)
                                            ->info('Length of generated MFA codes')
                                        ->end()
                                        ->scalarNode('code_expiration_time')
                                            ->defaultValue('PT60M')
                                            ->info('Code expiration time (ISO 8601 duration)')
                                        ->end()
                                        ->scalarNode('provider')
                                            ->defaultValue('App\Security\MFA\Email\EmailTwoFactorProvider')
                                            ->info('MFA provider class')
                                        ->end()
                                        ->scalarNode('generator')
                                            ->defaultValue('App\Security\MFA\Email\CodeGenerator')
                                            ->info('Code generator class')
                                        ->end()
                                    ->end()
                                ->end()
                                // You can easily add more MFA methods here:
                                // ->arrayNode('sms')
                                //     ->addDefaultsIfNotSet()
                                //     ->children()
                                //         ->integerNode('code_length')->defaultValue(4)->end()
                                //         ->scalarNode('expires_after')->defaultValue('PT15M')->end()
                                //         ->scalarNode('template')->defaultValue('security/sms-mfa-form.html.twig')->end()
                                //         ->scalarNode('provider')->defaultValue('App\Security\MFA\SMS\SMSTwoFactorProvider')->end()
                                //         ->scalarNode('generator')->defaultValue('App\Security\MFA\SMS\SMSCodeGenerator')->end()
                                //     ->end()
                                // ->end()
                            ->end()
                        ->end()
                        ->arrayNode('password_reset')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('signing_key')
                                    ->defaultValue('%env(string:APP_SECRET)%')
                                    ->info('Reset token signing key (Defaults to APP_SECRET)')
                                ->end()
                                ->integerNode('selector_length')
                                    ->defaultValue(20)
                                    ->min(10)
                                    ->max(20)
                                    ->info('Length of request token selector part')
                                ->end()
                                ->integerNode('verifier_length')
                                    ->defaultValue(20)
                                    ->min(10)
                                    ->max(80)
                                    ->info('Length of request token verifier part')
                                ->end()
                                ->scalarNode('token_expiration_time')
                                    ->defaultValue('PT60M')
                                    ->info('Token expiration time (ISO 8601 duration)')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('account_registration')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('signing_key')
                                    ->defaultValue('%env(string:APP_SECRET)%')
                                    ->info('Reset token signing key (Defaults to APP_SECRET)')
                                ->end()
                                ->integerNode('selector_length')
                                    ->defaultValue(20)
                                    ->min(10)
                                    ->max(20)
                                    ->info('Length of request token selector part')
                                ->end()
                                ->integerNode('verifier_length')
                                    ->defaultValue(20)
                                    ->min(10)
                                    ->max(80)
                                    ->info('Length of request token verifier part')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('emails')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('server_setup')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('subject')
                                    ->defaultValue('subject.server_setup')
                                    ->info('Subject for server setup email')
                                ->end()
                                ->scalarNode('template')
                                    ->defaultValue('emails/security/server_setup.html.twig')
                                    ->info('Template for server setup email')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('password_reset')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('url_template')
                                    ->defaultValue('/password-reset/{token}')
                                    ->info('URL template for password reset (use {token} placeholder)')
                                ->end()
                                ->scalarNode('subject')
                                    ->defaultValue('subject.password_reset')
                                    ->info('Subject for password reset email')
                                ->end()
                                ->scalarNode('template')
                                    ->defaultValue('emails/security/password_reset.html.twig')
                                    ->info('Template for password reset email')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('account_activation')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('url_template')
                                    ->defaultValue('/account-activation/{token}')
                                    ->info('URL template for account activation (use {token} placeholder)')
                                ->end()
                                ->scalarNode('subject')
                                    ->defaultValue('subject.account_activation')
                                    ->info('Subject for account activation email')
                                ->end()
                                ->scalarNode('template')
                                    ->defaultValue('emails/security/account_activation.html.twig')
                                    ->info('Template for account activation email')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('registration')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('url_template')
                                    ->defaultValue('/account-registration/{token}')
                                    ->info('URL template for account registration (use {token} placeholder)')
                                ->end()
                                ->scalarNode('subject')
                                    ->defaultValue('subject.account_registration')
                                    ->info('Subject for account registration email')
                                ->end()
                                ->scalarNode('template')
                                    ->defaultValue('emails/security/account_registration.html.twig')
                                    ->info('Template for account registration email')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('mfa')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('subject')
                                    ->defaultValue('subject.mfa')
                                    ->info('Subject for MFA email')
                                ->end()
                                ->scalarNode('template')
                                    ->defaultValue('security/mfa-form.html.twig')
                                    ->info('Template for MFA email')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('jwt')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('private_key')
                            ->defaultValue('%env(resolve:JWT_PRIVATE_KEY)%')
                            ->info('JWT private key')
                        ->end()
                        ->scalarNode('public_key')
                            ->defaultValue('%env(resolve:JWT_PUBLIC_KEY)%')
                            ->info('JWT public key')
                        ->end()
                        ->scalarNode('algorithm')
                            ->defaultValue('HS256')
                            ->info('JWT algorithm')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('oauth_server')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('issuer')
                            ->defaultValue('mycelium')
                            ->info('Issuer for OAuth server')
                        ->end()
                        ->scalarNode('authorization_code_time')
                            ->defaultValue('PT10M')
                            ->info('Authorization code time (ISO 8601 duration)')
                        ->end()
                        ->scalarNode('access_token_time')
                            ->defaultValue('PT1H')
                            ->info('Access token time (ISO 8601 duration)')
                        ->end()
                        ->scalarNode('refresh_token_time')
                            ->defaultValue('P1M')
                            ->info('Refresh token time (ISO 8601 duration)')
                        ->end()
                        ->scalarNode('id_token_time')
                            ->defaultValue('PT1H')
                            ->info('ID token time (ISO 8601 duration)')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
